# DO NOT EDIT THIS FILE!
#
# Python module EncryptDecrypt generated by omniidl

import omniORB
omniORB.updateModule("EncryptDecrypt")

# ** 1. Stub files contributing to this module
import atividade_idl

# ** 2. Sub-modules

# ** 3. End
