package EncryptDecrypt;


/**
* EncryptDecrypt/EDStringHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from atividade.idl
* Sábado, 19 de Outubro de 2019 11h45min15s BRT
*/

abstract public class EDStringHelper
{
  private static String  _id = "IDL:EncryptDecrypt/EDString:1.0";

  public static void insert (org.omg.CORBA.Any a, EncryptDecrypt.EDString that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EncryptDecrypt.EDString extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EncryptDecrypt.EDStringHelper.id (), "EDString");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EncryptDecrypt.EDString read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EDStringStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EncryptDecrypt.EDString value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EncryptDecrypt.EDString narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EncryptDecrypt.EDString)
      return (EncryptDecrypt.EDString)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EncryptDecrypt._EDStringStub stub = new EncryptDecrypt._EDStringStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static EncryptDecrypt.EDString unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EncryptDecrypt.EDString)
      return (EncryptDecrypt.EDString)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EncryptDecrypt._EDStringStub stub = new EncryptDecrypt._EDStringStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
