package EncryptDecrypt;

/**
* EncryptDecrypt/EDStringHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from atividade.idl
* Sábado, 19 de Outubro de 2019 11h45min15s BRT
*/

public final class EDStringHolder implements org.omg.CORBA.portable.Streamable
{
  public EncryptDecrypt.EDString value = null;

  public EDStringHolder ()
  {
  }

  public EDStringHolder (EncryptDecrypt.EDString initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EncryptDecrypt.EDStringHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EncryptDecrypt.EDStringHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EncryptDecrypt.EDStringHelper.type ();
  }

}
