package EncryptDecrypt;


/**
* EncryptDecrypt/EDString.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from atividade.idl
* Sábado, 19 de Outubro de 2019 11h45min15s BRT
*/

public interface EDString extends EDStringOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EDString
