package EncryptDecrypt;


/**
* EncryptDecrypt/EDStringOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from atividade.idl
* Sábado, 19 de Outubro de 2019 11h45min15s BRT
*/

public interface EDStringOperations 
{
  String echoString (String msg);
} // interface EDStringOperations
