package EncryptDecrypt;


/**
* EncryptDecrypt/EDStringPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from atividade.idl
* Sábado, 19 de Outubro de 2019 11h45min15s BRT
*/

public abstract class EDStringPOA extends org.omg.PortableServer.Servant
 implements EncryptDecrypt.EDStringOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("echoString", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // EncryptDecrypt/EDString/echoString
       {
         String msg = in.read_string ();
         String $result = null;
         $result = this.echoString (msg);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:EncryptDecrypt/EDString:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public EDString _this() 
  {
    return EDStringHelper.narrow(
    super._this_object());
  }

  public EDString _this(org.omg.CORBA.ORB orb) 
  {
    return EDStringHelper.narrow(
    super._this_object(orb));
  }


} // class EDStringPOA
